# Site settings
name: Theo Moss
author: Theo Moss
title: Paper Beats Rock
subtitle: A Bahamian Digital Media Center
description: A Bahamian Digital Media Center
slogan:
keywords:
language: 'en'

url: https://tmoss4.github.io
baseurl: /pbr
imgurl: https://tmoss4.github.io/pbr/img/

github: http://www.github.com/tmoss4
facebook: https://www.facebook.com/theophilus.moss
linkedin: https://www.linkedin.com/in/tmoss4
email: moss.theophilus@gmail.com
location: 
disqus: paper-beats-rock-digital-media-center

cover: /assets/cover.png
logo: /assets/logo.png

# Build settings
markdown: kramdown

# Google analytics
google_analytics_tracking_id: UA-88742570-2
google_site_verification:  'google79a5f690135ab0dc.html'

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

